services:
    immich_server:
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.immich.rule=Host(`immich.${MY_DOMAIN}`)'
        - 'traefik.http.routers.immich.entryPoints=websecure'

    ocis:
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.ocis.rule=Host(`ocis.${MY_DOMAIN}`)'
        - 'traefik.http.routers.ocis.entryPoints=websecure'
        - 'traefik.http.services.ocis.loadbalancer.server.port=9200'
      environment:
        OCIS_URL: https://ocis.${MY_DOMAIN}
    
    paperless:
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.paperless.rule=Host(`paperless.${MY_DOMAIN}`)'
        - 'traefik.http.routers.paperless.entryPoints=websecure'
      environment:
        PAPERLESS_URL: https://paperless.${MY_DOMAIN}

    tandoor:
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.tandoor.rule=Host(`tandoor.${MY_DOMAIN}`)'
        - 'traefik.http.routers.tandoor.entryPoints=websecure'

    pihole:
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.pihole.rule=Host(`pihole.${MY_DOMAIN}`)'
        - 'traefik.http.routers.pihole.entryPoints=websecure'

    homeassistant:
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.ha.rule=Host(`ha.${MY_DOMAIN}`)'
        - 'traefik.http.routers.ha.entryPoints=websecure'
        - 'traefik.http.services.ha.loadbalancer.server.port=8123'

    emby:
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.emby.rule=Host(`emby.${MY_DOMAIN}`)'
        - 'traefik.http.routers.emby.entryPoints=websecure'
        - 'traefik.http.services.emby.loadbalancer.server.port=8096'
    
    filebrowser:
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.filebrowser.rule=Host(`fb.${MY_DOMAIN}`)'
        - 'traefik.http.routers.filebrowser.entryPoints=websecure'
